"""product images field added & rating unique handle

Revision ID: 450dde4f7e7e
Revises: 036f0244796c
Create Date: 2025-09-03 15:44:31.129978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450dde4f7e7e'
down_revision: Union[str, Sequence[str], None] = '036f0244796c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('images', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_product_user_rating', 'rating', ['product_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_user_rating', 'rating', type_='unique')
    op.drop_column('product', 'images')
    # ### end Alembic commands ###
